default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      project: "Example/Example.xcodeproj",
      clean: true,
      output_types: "",
      derived_data_path: "Build",
      code_coverage: true,
      devices: ["iPhone 8"],
      testplan: "FullTests"
    )

    danger(
      dangerfile: "./Dangerfile",
      github_api_token: ENV["DANGER_GITHUB_API_TOKEN"],
      verbose: true
    )
  end
end
