default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    sh("swift package generate-xcodeproj")

    scan(
      workspace: "Example/Example.xcworkspace",
      scheme: "Example",
      clean: true,
      output_types: "",
      derived_data_path: "Build",
      code_coverage: true,
      devices: ["iPhone 8"],
      testplan: "FullTests",
      xcargs: "-parallel-testing-enabled YES -parallel-testing-worker-count 4 -quiet",
      disable_xcpretty: true
    )

    danger(
      dangerfile: "./Dangerfile",
      github_api_token: ENV["DANGER_GITHUB_API_TOKEN"],
      verbose: true
    )
  end
end
