name: Format

on:
  pull_request:
    branches:
      - "*"

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: brew install st3ffwo3/formulae/swift-format
      - name: Format
        run: make format
      - uses: nelonoel/branch-name@v1.0.1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
          branch: ${BRANCH_NAME}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
