name: test

on:
  pull_request_target:
    branches:
      - "*"

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: Run tests
        run: make test

      - name: Danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ResultBundle
          path: ./coverage/*.xcresult
          if-no-files-found: warn
          retention-days: 5

      - name: Clean up
        if: ${{ always() }}
        run: make cleanup
