name: test

on:
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: Run tests
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make test

      - uses: actions/upload-artifact@v2
        with:
          path: /Users/**/work/swift-composable-navigator/swift-composable-navigator/Build/Logs/Test/*.xcresult

      - name: Clean up
        run: make cleanup
