name: test

on:
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test
      - name: Danger
        uses: danger/swift@3.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
