name: test

on:
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install DangerJS
        run: npm install -g danger

      - name: Run tests
        run: make test

      - name: Danger
        run: swift run danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ResultBundle
          path: ./coverage/*.xcresult
          if-no-files-found: warn
          retention-days: 5

      - name: Clean up
        if: ${{ always() }}
        run: make cleanup
